project:
  type: website
  output-dir: docs

website:
  title: "Observatorio del Cambio Religioso en Chile"
  navbar:
    left:
      - text: Inicio
        href: index.qmd
      - text: An√°lisis
        href: analisis.qmd
      - text: Datos
        href: datos.qmd
      - text: Papers
        href: papers.qmd
      - text: Sobre el Proyecto
        href: about.qmd

format:
  html:
    theme: litera
    css: styles.css
    toc: true